vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Dec 2007 12:02:22 -0000
vti_extenderversion:SR|4.0.2.8912
vti_cacheddtm:TX|14 Dec 2007 12:02:22 -0000
vti_filesize:IR|17567
vti_cachedlinkinfo:VX|Q|../css/style.css S|../Image/bgact.gif S|../Image/sieradonline.gif S|../../GeneratedItems/current.js H|../contact.asp H|../karir.asp H|../link.asp H|<%=\\ MM_Logout\\ %> S|../../BREEDING/img/spacer.gif H|createcapex.asp S|../Image/CreateCapex.gif D|clsid:D27CDB6E-AE6D-11cf-96B8-444553540000 D|http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab S|../Animasi/anakayam.swf H|Infocapexappr.asp S|../Image/ApprovalCapex.gif H|ListCapexApproved.asp S|../Image/CreateAOC.gif H|InfoAOCappr.asp S|../Image/Approvalaoc.gif H|hold\\ capex.asp S|../Image/holdcapex.gif H|hold\\ AOC.asp S|../Image/holdAoc.gif H|SearchNoAOCforPayment.asp S|../Image/Estimation.gif H|Payman\\ actual.asp S|../Image/Actual.gif S|../../BREEDING/img/spacer.gif S|../../img/bg.gif S|../Image/spacer.jpg S|../../img/garis1.gif S|../../img/garis1.gif A|<%=MM_LoginAction%> S|../../img/garis1.gif S|../../img/garis1.gif H|Sman.asp H|Activity.asp H|../Reports/reportListing.asp S|../Image/bannerrg.jpg
vti_cachedsvcrellinks:VX|FQUS|capex/css/style.css FSUS|capex/Image/bgact.gif FSUS|capex/Image/sieradonline.gif NSUS|GeneratedItems/current.js NHUS|capex/contact.asp NHUS|capex/karir.asp NHUS|capex/link.asp UHUS|<%=\\ MM_Logout\\ %> NSUS|BREEDING/img/spacer.gif FHUS|capex/mainmenu/createcapex.asp FSUS|capex/Image/CreateCapex.gif NDUS|clsid:D27CDB6E-AE6D-11cf-96B8-444553540000 NDHS|http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab FSUS|capex/Animasi/anakayam.swf FHUS|capex/mainmenu/Infocapexappr.asp FSUS|capex/Image/ApprovalCapex.gif FHUS|capex/mainmenu/ListCapexApproved.asp FSUS|capex/Image/CreateAOC.gif FHUS|capex/mainmenu/InfoAOCappr.asp FSUS|capex/Image/Approvalaoc.gif FHUS|capex/mainmenu/hold\\ capex.asp FSUS|capex/Image/holdcapex.gif FHUS|capex/mainmenu/hold\\ AOC.asp FSUS|capex/Image/holdAoc.gif FHUS|capex/mainmenu/SearchNoAOCforPayment.asp FSUS|capex/Image/Estimation.gif FHUS|capex/mainmenu/Payman\\ actual.asp FSUS|capex/Image/Actual.gif NSUS|BREEDING/img/spacer.gif NSUS|img/bg.gif FSUS|capex/Image/spacer.jpg NSUS|img/garis1.gif NSUS|img/garis1.gif UAUS|<%=MM_LoginAction%> NSUS|img/garis1.gif NSUS|img/garis1.gif FHUS|capex/mainmenu/Sman.asp FHUS|capex/MainMenu/Activity.asp FHUS|capex/Reports/reportListing.asp FSUS|capex/Image/bannerrg.jpg
vti_cachedtitle:SR|:: Approval AOC ::
vti_title:SR|:: Approval AOC ::
vti_cachedbodystyle:SR|<body background="../Image/bgact.gif" onLoad="MM_preloadImages('../Image/CreateCapex_on.gif','../Image/ApprovalCapex_on.gif','../Image/CreateAOC_on.gif','../Image/Approvalaoc_on.gif','../Image/holdcapex_on.gif','../Image/holdAoc_on.gif','../Image/Estimation_on.gif','../Image/Actual_on.gif')">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1
vti_backlinkinfo:VX|capex/mainmenu/appraoc.asp capex/mainmenu/appraoc1.asp
