vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|15 Jan 2006 18:34:08 -0000
vti_extenderversion:SR|4.0.2.8912
vti_cacheddtm:TX|15 Jan 2006 18:34:08 -0000
vti_filesize:IR|11658
vti_cachedlinkinfo:VX|S|MainMenu/mm_menu.js S|../Image/bg.gif S|../Image/banner2.gif H|../Search/Search.asp H|<%=\\ MM_Logout\\ %> H|MasterBudget.asp S|../Image/budget.gif H|MasterCompany.asp S|../Image/company.gif H|MasterCurrency.asp S|../Image/currency.gif H|MasterDivisi.asp S|../Image/divisi.gif H|MasterUser.asp S|../Image/user.gif H|MasterVendor.asp S|../Image/vendor.gif H|ListBudget.asp H|ListCompany.asp H|ListCurrency.asp H|ListDivisi.asp H|ListUser.asp H|ListVendor.asp
vti_cachedsvcrellinks:VX|NSUS|capex/MainMenu/MainMenu/mm_menu.js FSUS|capex/Image/bg.gif FSUS|capex/Image/banner2.gif FHUS|capex/Search/Search.asp UHUS|<%=\\ MM_Logout\\ %> FHUS|capex/MainMenu/MasterBudget.asp FSUS|capex/Image/budget.gif FHUS|capex/MainMenu/MasterCompany.asp FSUS|capex/Image/company.gif FHUS|capex/MainMenu/MasterCurrency.asp FSUS|capex/Image/currency.gif FHUS|capex/MainMenu/MasterDivisi.asp FSUS|capex/Image/divisi.gif FHUS|capex/MainMenu/MasterUser.asp FSUS|capex/Image/user.gif FHUS|capex/MainMenu/MasterVendor.asp FSUS|capex/Image/vendor.gif FHUS|capex/MainMenu/ListBudget.asp FHUS|capex/MainMenu/ListCompany.asp FHUS|capex/MainMenu/ListCurrency.asp FHUS|capex/MainMenu/ListDivisi.asp FHUS|capex/MainMenu/ListUser.asp FHUS|capex/MainMenu/ListVendor.asp
vti_cachedtitle:SR|:: Main Page ::
vti_title:SR|:: Main Page ::
vti_cachedbodystyle:SR|<body onLoad="MM_preloadImages('Image/SysMan.gif','../Image/budget_over.gif','../Image/company_over.gif','../Image/currency_over.gif','../Image/divisi_over.gif','../Image/user_over.gif','../Image/vendor_over.gif')">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1
vti_backlinkinfo:VX|capex/mainmenu/confirmapproval.asp capex/mainmenu/\\ listphargadetail.asp capex/mainmenu/confirmstatusappraoc.asp capex/mainmenu/searchnoaocforvendor.asp capex/mainmenu/browse\\ capex.asp capex/mainmenu/confirmappraoc.asp capex/mainmenu/createaoc.asp capex/mainmenu/payman\\ actual.asp capex/mainmenu/appraoc.asp capex/mainmenu/browse\\ aocstatus.asp capex/mainmenu/holdstatuscapex.asp capex/mainmenu/listpaymentactual.asp capex/mainmenu/searchnoaoc.asp capex/mainmenu/capexapproval.asp capex/mainmenu/listpharga.asp capex/mainmenu/prosesapproval.asp capex/mainmenu/viewaocdetail.asp capex/mainmenu/create\\ capex.asp capex/mainmenu/listcapexapproved.asp capex/mainmenu/payman\\ estimation.asp capex/mainmenu/payment.asp capex/mainmenu/browse\\ capexappr.asp capex/mainmenu/fail_confirm.asp capex/mainmenu/infoaocappr.asp capex/mainmenu/allcapexdetail.asp capex/mainmenu/aocapproval.asp capex/mainmenu/listpaymentestimasi.asp capex/mainmenu/pilihvendor.asp capex/mainmenu/activity.asp capex/mainmenu/browse\\ aoc.asp capex/mainmenu/confirmapprovaaocl.asp capex/mainmenu/create\\ aocdetail.asp capex/mainmenu/createcapexd.asp capex/mainmenu/mainpage.asp capex/mainmenu/phargahd.asp capex/mainmenu/searchforlistpaymentactual.asp capex/mainmenu/searchnoaoc\\ listphargadetail.asp capex/mainmenu/\\ browse\\ capexstatus.asp capex/mainmenu/createcapex.asp capex/mainmenu/hold\\ aoc.asp capex/mainmenu/phargadt.asp capex/mainmenu/allaocdetail.asp capex/mainmenu/appraoc1.asp capex/mainmenu/approvalaoc.asp capex/mainmenu/approvalcapexdetail.asp capex/mainmenu/create\\ aoc.asp capex/mainmenu/detail\\ aoc.asp capex/mainmenu/infocapexappr.asp capex/mainmenu/pilihvendor3.asp capex/mainmenu/apprcapex.asp capex/mainmenu/holdstatusaoc.asp capex/mainmenu/searchnocapex.asp capex/mainmenu/approvalcapex.asp capex/mainmenu/detail\\ capex.asp capex/mainmenu/pilihvendor2.asp capex/mainmenu/searchnoaocforpayment.asp capex/mainmenu/apprcapex1.asp capex/mainmenu/confirmappr.asp capex/mainmenu/createpayman\\ actual.asp capex/mainmenu/hold\\ capex.asp
